language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install
  - cd public

script: phpunit --configuration ../phpunit.xml

matrix:
  allow_failures:
    - php: 5.5
    - php: hhvm
    - php: nightly
  fast_finish: true
